### ISSUE TITLE
drf-model-serializer-meta-attribute raise IndexError

### ISSUE THREAD

**Issue by idr-yous** [kalekseev/django-extra-checks#34]
### Description
I am encountering an IndexError: list index out of range when using the `drf-model-serializer-meta-attribute` check in my `CustomUserCreateSerializer` class, which inherits from `UserCreateSerializer`.

**Parent Class Code**
Here is the implementation of the parent class `UserCreateSerializer`:

```
class UserCreateSerializer(UserCreateMixin, serializers.ModelSerializer):
    password = serializers.CharField(style={"input_type": "password"}, write_only=True)

    default_error_messages = {
        "cannot_create_user": settings.CONSTANTS.messages.CANNOT_CREATE_USER_ERROR
    }

    class Meta:
        model = User
        fields = tuple(User.REQUIRED_FIELDS) + (
            settings.LOGIN_FIELD,
            settings.USER_ID_FIELD,
            "password",
        )

     # rest of code
```

**Custom Class Code**
Here is the implementation of my custom class `CustomUserCreateSerializer`:

```
class CustomUserCreateSerializer(UserCreateSerializer):

    def validate(self, attrs):
        attrs = super().validate(attrs)

        user = User(**attrs)

        # This will call the clean() method
        user.full_clean()

        return attrs
```

**EXTRA_CHECKS Setting**
Below is my EXTRA_CHECKS setting:
```
EXTRA_CHECKS = {
    "checks": [
        # other configurations
        # require `verbose_name` and `verbose_name_plural` for all models
        {
            "id": "model-meta-attribute",
            "attrs": ["verbose_name", "verbose_name_plural"],
            "level": "CRITICAL",
        },
        # ModelSerializer's extra_kwargs must not include fields that are specified on serializer.
        "drf-model-serializer-extra-kwargs",
        # Each ModelSerializer.Meta must have all attributes specified in attrs
        {"id": "drf-model-serializer-meta-attribute", "attrs": ["read_only_fields"]},
    ],
}
```

**Error Message**
Here is the full error message that I encountered:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
    File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
        self.run()
    File "/usr/local/lib/python3.11/threading.py", line 982, in run
        self._target(*self._args, **self._kwargs)


    File "/py/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
        fn(*args, **kwargs)
    File "/py/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
        self.check(display_num_errors=True)
    File "/py/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
        all_issues = checks.run_checks(
                    ^^^^^^^^^^^^^^^^^^
    File "/py/lib/python3.11/site-packages/django/core/checks/registry.py", line 94, in run_checks
    
errors.extend(new_errors)
    File "/py/lib/python3.11/site-packages/extra_checks/checks/drf_serializer_checks.py", line 149, in check_drf_serializers
        yield from check(s, comment_provider)
    File "/py/lib/python3.11/site-packages/extra_checks/checks/base_checks.py", line 54, in __call__
        if not ast or (error.id and not ast.is_disabled_by_comment(error.id)):
 
       ^^^^^^^^^^^
^
^
^^^^^^^^^^^^^^^^^^^^^^^
  File "/py/lib/python3.11/site-packages/extra_checks/checks/drf_serializer_checks.py", line 47, in is_disabled_by_comment
    line = self._get_line()
 
          ^^^^^^^^^^^^^^^^
  File "/py/lib/python3.11/site-packages/extra_checks/checks/drf_serializer_checks.py", line 59, in _get_line
    return sorted(
           ^^^^^^^
IndexError
: list index out of range
```

I attempted to disable this check by using the following directive:
```
# extra-checks-disable-next-line model-attribute, model-meta-attribute, drf-model-serializer-meta-attribute
class CustomUserCreateSerializer(UserCreateSerializer):
    # rest of code

```

However, I still encountered the same error. The issue persisted until I completely disabled the `drf-model-serializer-meta-attribute check` in `EXTRA_CHECKS`.

The other solution that worked for me was to redefine the Meta class in the child class, but this results in duplication.

**Comment by kalekseev** [comment]
@idr-yous thanks for the report, fixed in 0.14.1
